"""version1

Revision ID: 2712de28cc7b
Revises: be7cbbb456ea
Create Date: 2022-11-11 20:34:50.755778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2712de28cc7b'
down_revision = 'be7cbbb456ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
