"""v1

Revision ID: 67059fec8f20
Revises: 
Create Date: 2022-10-31 19:25:52.454411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67059fec8f20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_attempt_data_tbl')
    op.drop_table('group_data_tbl')
    op.drop_table('link_data_tbl')
    op.drop_table('team_data_tbl')
    op.drop_table('address_data_tbl')
    op.drop_table('ticket_data_tbl')
    op.drop_table('gender_data_tbl')
    op.drop_table('user_data_table')
    op.drop_table('permission_data_tbl')
    op.drop_table('external_login_data_tbl')
    op.drop_table('membership_data_tbl')
    op.create_index(op.f('ix_account_data_tbl_ac_id'), 'account_data_tbl', ['ac_id'], unique=False)
    op.create_index(op.f('ix_password_data_tbl_pass_id'), 'password_data_tbl', ['pass_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_data_tbl_pass_id'), table_name='password_data_tbl')
    op.drop_index(op.f('ix_account_data_tbl_ac_id'), table_name='account_data_tbl')
    op.create_table('membership_data_tbl',
    sa.Column('mem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('membership_type', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=False),
    sa.Column('perm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('mem_id', name='membership_data_tbl_pkey')
    )
    op.create_table('external_login_data_tbl',
    sa.Column('ext_login_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_name', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('wse_endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ext_provider_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ext_login_id', name='external_login_data_tbl_pkey')
    )
    op.create_table('permission_data_tbl',
    sa.Column('perm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_type', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=False),
    sa.Column('p_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('p_write', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('p_publish', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('p_premium', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('perm_id', name='permission_data_tbl_pkey')
    )
    op.create_table('user_data_table',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ac_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('firstname', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('lastname', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('gender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone_c_code', postgresql.ARRAY(sa.VARCHAR(length=5)), autoincrement=False, nullable=True),
    sa.Column('phone_no', postgresql.ARRAY(sa.VARCHAR(length=12)), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='user_data_table_pkey')
    )
    op.create_table('gender_data_tbl',
    sa.Column('gender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender_name', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gender_id', name='gender_data_tbl_pkey')
    )
    op.create_table('ticket_data_tbl',
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ac_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticket_type', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attachement', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('priority', postgresql.ARRAY(sa.VARCHAR(length=5)), autoincrement=False, nullable=False),
    sa.Column('is_open', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ticket_id', name='ticket_data_tbl_pkey')
    )
    op.create_table('address_data_tbl',
    sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address1', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('address2', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('city', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('region', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('postcode', postgresql.ARRAY(sa.VARCHAR(length=10)), autoincrement=False, nullable=True),
    sa.Column('country', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('address_id', name='address_data_tbl_pkey')
    )
    op.create_table('team_data_tbl',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ac_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('team_id', name='team_data_tbl_pkey')
    )
    op.create_table('link_data_tbl',
    sa.Column('link_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filepath', postgresql.ARRAY(sa.VARCHAR(length=260)), autoincrement=False, nullable=False),
    sa.Column('filename', postgresql.ARRAY(sa.VARCHAR(length=15)), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('link_id', name='link_data_tbl_pkey')
    )
    op.create_table('group_data_tbl',
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ac_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_name', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('group_id', name='group_data_tbl_pkey')
    )
    op.create_table('login_attempt_data_tbl',
    sa.Column('login_att_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ac_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tried_password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ip_address', postgresql.ARRAY(sa.VARCHAR(length=15)), autoincrement=False, nullable=True),
    sa.Column('browser_type', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('is_success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('login_att_id', name='login_attempt_data_tbl_pkey')
    )
    # ### end Alembic commands ###
