"""empty message

Revision ID: 9fb060cdeebd
Revises: d280193383f7
Create Date: 2022-11-16 21:11:10.799248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb060cdeebd'
down_revision = 'd280193383f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
