"""version1

Revision ID: be7cbbb456ea
Revises: 7de48517686b
Create Date: 2022-11-11 20:32:44.623830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7cbbb456ea'
down_revision = '7de48517686b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
